spring:
  application:
    name: Fitpin
  servlet:
    multipart:
      enabled: true #파일 업로드 활성화
      max-file-size: 20MB # 파일 최대 크기
      max-request-size: 20MB #요청 최대 크기
  datasource:
    hikari:
      jdbc-url:
      username: 
      password:
      driver-class-name: org.mariadb.jdbc.Driver
      connection-test-query: SELECT NOW() FROM dual

file:
  upload-dir: home/fitpinImg

# MyBatis setting
mybatis:
  #mapper-locations: classpath:/mappers/*.xml
  mapper-locations: classpath:/mappers/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true

# SSH setting
ssh:
  user: 
  host: 
  port: 22
  private-key: src/main/resources/dbSSL/AWSkey.ppk
  remote-host: 
  local-port: 3307
  remote-port: 3306

# JPA setting
spring.jpa.hibernate.ddl-auto: update

#Spring boot Logging

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.mybatis: DEBUG
