spring:
  application:
    name: Fitpin
  datasource:
    hikari:
      jdbc-url:
      username: 
      password:
      driver-class-name: org.mariadb.jdbc.Driver
      connection-test-query: SELECT NOW() FROM dual

# MyBatis setting
mybatis:
  #mapper-locations: classpath:/mappers/*.xml
  mapper-locations: classpath:/mappers/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true

# SSH setting
ssh:
  user: 
  host: 
  port: 22
  private-key: src/main/resources/dbSSL/AWSkey.ppk
  remote-host: 
  local-port: 3307
  remote-port: 3306

# JPA setting
spring.jpa.hibernate.ddl-auto: update

#Spring boot Logging

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.mybatis: DEBUG
